
CREATE TABLE IF NOT EXISTS users (
id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
name varchar(255)   NOT NULL,
email varchar(255)   NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id),
CONSTRAINT uc_users_email UNIQUE (email)
 );

CREATE TABLE IF NOT EXISTS requests (
id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
description varchar(512) NOT NULL,
requester_id bigint   NOT null REFERENCES users(id) ON DELETE CASCADE,
created timestamp NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (id)
    );


CREATE TABLE IF NOT EXISTS items (
id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
name varchar(255)   NOT NULL,
description varchar(512)   NOT NULL,
available boolean   NOT NULL,
owner_id bigint   NOT null REFERENCES users(id) ON DELETE CASCADE,
request_id bigint REFERENCES requests(id) ,
CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
start_date timestamp WITHOUT TIME ZONE NOT NULL,
end_date timestamp WITHOUT TIME ZONE NOT NULL,
booker_id bigint   NOT null REFERENCES users(id) ON DELETE CASCADE,
item_id bigint   NOT null REFERENCES items(id) ON DELETE CASCADE,
status varchar(20)   NOT NULL,
CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
id bigint GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
text varchar(512)   NOT NULL,
author_id bigint   NOT null REFERENCES users(id) ON DELETE CASCADE,
item_id bigint   NOT null REFERENCES items(id) ON DELETE CASCADE,
created timestamp   NOT NULL,
CONSTRAINT pk_comments PRIMARY KEY (id)
);









